// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgencyStatus int32

const (
	AgencyStatus_PENDING     AgencyStatus = 0
	AgencyStatus_ACTIVATED   AgencyStatus = 1
	AgencyStatus_DEACTIVATED AgencyStatus = 2
)

var AgencyStatus_name = map[int32]string{
	0: "PENDING",
	1: "ACTIVATED",
	2: "DEACTIVATED",
}

var AgencyStatus_value = map[string]int32{
	"PENDING":     0,
	"ACTIVATED":   1,
	"DEACTIVATED": 2,
}

func (x AgencyStatus) String() string {
	return proto.EnumName(AgencyStatus_name, int32(x))
}

func (AgencyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{0}
}

type Gender int32

const (
	Gender_MALE    Gender = 0
	Gender_FEMALE  Gender = 1
	Gender_UNKNOWN Gender = 2
)

var Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
	2: "UNKNOWN",
}

var Gender_value = map[string]int32{
	"MALE":    0,
	"FEMALE":  1,
	"UNKNOWN": 2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{1}
}

type CreateAgencyRequest struct {
	// information agency
	Name               string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address            string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TaxCode            string `protobuf:"bytes,3,opt,name=taxCode,proto3" json:"taxCode,omitempty"`
	RepresentativeName string `protobuf:"bytes,4,opt,name=representativeName,proto3" json:"representativeName,omitempty"`
	// information agent root
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	PhoneVerify          string   `protobuf:"bytes,7,opt,name=phoneVerify,proto3" json:"phoneVerify,omitempty"`
	EmailVerify          string   `protobuf:"bytes,8,opt,name=emailVerify,proto3" json:"emailVerify,omitempty"`
	QuestionSecurity     string   `protobuf:"bytes,9,opt,name=questionSecurity,proto3" json:"questionSecurity,omitempty"`
	AnswerSecurity       string   `protobuf:"bytes,10,opt,name=answerSecurity,proto3" json:"answerSecurity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgencyRequest) Reset()         { *m = CreateAgencyRequest{} }
func (m *CreateAgencyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAgencyRequest) ProtoMessage()    {}
func (*CreateAgencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{0}
}

func (m *CreateAgencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgencyRequest.Unmarshal(m, b)
}
func (m *CreateAgencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgencyRequest.Marshal(b, m, deterministic)
}
func (m *CreateAgencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgencyRequest.Merge(m, src)
}
func (m *CreateAgencyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAgencyRequest.Size(m)
}
func (m *CreateAgencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgencyRequest proto.InternalMessageInfo

func (m *CreateAgencyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAgencyRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateAgencyRequest) GetTaxCode() string {
	if m != nil {
		return m.TaxCode
	}
	return ""
}

func (m *CreateAgencyRequest) GetRepresentativeName() string {
	if m != nil {
		return m.RepresentativeName
	}
	return ""
}

func (m *CreateAgencyRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateAgencyRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateAgencyRequest) GetPhoneVerify() string {
	if m != nil {
		return m.PhoneVerify
	}
	return ""
}

func (m *CreateAgencyRequest) GetEmailVerify() string {
	if m != nil {
		return m.EmailVerify
	}
	return ""
}

func (m *CreateAgencyRequest) GetQuestionSecurity() string {
	if m != nil {
		return m.QuestionSecurity
	}
	return ""
}

func (m *CreateAgencyRequest) GetAnswerSecurity() string {
	if m != nil {
		return m.AnswerSecurity
	}
	return ""
}

type UpdateAgencyRequest struct {
	AgencyId             int64        `protobuf:"varint,1,opt,name=agencyId,proto3" json:"agencyId,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string       `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	TaxCode              string       `protobuf:"bytes,4,opt,name=taxCode,proto3" json:"taxCode,omitempty"`
	RepresentativeName   string       `protobuf:"bytes,5,opt,name=representativeName,proto3" json:"representativeName,omitempty"`
	Status               AgencyStatus `protobuf:"varint,6,opt,name=status,proto3,enum=account.AgencyStatus" json:"status,omitempty"`
	CardNumber           string       `protobuf:"bytes,7,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateAgencyRequest) Reset()         { *m = UpdateAgencyRequest{} }
func (m *UpdateAgencyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAgencyRequest) ProtoMessage()    {}
func (*UpdateAgencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{1}
}

func (m *UpdateAgencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAgencyRequest.Unmarshal(m, b)
}
func (m *UpdateAgencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAgencyRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAgencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAgencyRequest.Merge(m, src)
}
func (m *UpdateAgencyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAgencyRequest.Size(m)
}
func (m *UpdateAgencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAgencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAgencyRequest proto.InternalMessageInfo

func (m *UpdateAgencyRequest) GetAgencyId() int64 {
	if m != nil {
		return m.AgencyId
	}
	return 0
}

func (m *UpdateAgencyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateAgencyRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpdateAgencyRequest) GetTaxCode() string {
	if m != nil {
		return m.TaxCode
	}
	return ""
}

func (m *UpdateAgencyRequest) GetRepresentativeName() string {
	if m != nil {
		return m.RepresentativeName
	}
	return ""
}

func (m *UpdateAgencyRequest) GetStatus() AgencyStatus {
	if m != nil {
		return m.Status
	}
	return AgencyStatus_PENDING
}

func (m *UpdateAgencyRequest) GetCardNumber() string {
	if m != nil {
		return m.CardNumber
	}
	return ""
}

type GetAgencyRequest struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string       `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TaxCode              string       `protobuf:"bytes,3,opt,name=taxCode,proto3" json:"taxCode,omitempty"`
	RepresentativeName   string       `protobuf:"bytes,4,opt,name=representativeName,proto3" json:"representativeName,omitempty"`
	Page                 *PageRequest `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAgencyRequest) Reset()         { *m = GetAgencyRequest{} }
func (m *GetAgencyRequest) String() string { return proto.CompactTextString(m) }
func (*GetAgencyRequest) ProtoMessage()    {}
func (*GetAgencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{2}
}

func (m *GetAgencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgencyRequest.Unmarshal(m, b)
}
func (m *GetAgencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgencyRequest.Marshal(b, m, deterministic)
}
func (m *GetAgencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgencyRequest.Merge(m, src)
}
func (m *GetAgencyRequest) XXX_Size() int {
	return xxx_messageInfo_GetAgencyRequest.Size(m)
}
func (m *GetAgencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgencyRequest proto.InternalMessageInfo

func (m *GetAgencyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetAgencyRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetAgencyRequest) GetTaxCode() string {
	if m != nil {
		return m.TaxCode
	}
	return ""
}

func (m *GetAgencyRequest) GetRepresentativeName() string {
	if m != nil {
		return m.RepresentativeName
	}
	return ""
}

func (m *GetAgencyRequest) GetPage() *PageRequest {
	if m != nil {
		return m.Page
	}
	return nil
}

type GetAgencyResponse struct {
	Page                 *PageResponse `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Items                []*Agency     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetAgencyResponse) Reset()         { *m = GetAgencyResponse{} }
func (m *GetAgencyResponse) String() string { return proto.CompactTextString(m) }
func (*GetAgencyResponse) ProtoMessage()    {}
func (*GetAgencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{3}
}

func (m *GetAgencyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgencyResponse.Unmarshal(m, b)
}
func (m *GetAgencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgencyResponse.Marshal(b, m, deterministic)
}
func (m *GetAgencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgencyResponse.Merge(m, src)
}
func (m *GetAgencyResponse) XXX_Size() int {
	return xxx_messageInfo_GetAgencyResponse.Size(m)
}
func (m *GetAgencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgencyResponse proto.InternalMessageInfo

func (m *GetAgencyResponse) GetPage() *PageResponse {
	if m != nil {
		return m.Page
	}
	return nil
}

func (m *GetAgencyResponse) GetItems() []*Agency {
	if m != nil {
		return m.Items
	}
	return nil
}

type Agency struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string       `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TaxCode              string       `protobuf:"bytes,3,opt,name=taxCode,proto3" json:"taxCode,omitempty"`
	RepresentativeName   string       `protobuf:"bytes,4,opt,name=representativeName,proto3" json:"representativeName,omitempty"`
	Status               AgencyStatus `protobuf:"varint,5,opt,name=status,proto3,enum=account.AgencyStatus" json:"status,omitempty"`
	CreatedAt            string       `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	CreatedBy            string       `protobuf:"bytes,7,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	LastModifiedAt       string       `protobuf:"bytes,8,opt,name=lastModifiedAt,proto3" json:"lastModifiedAt,omitempty"`
	LastModifiedBy       string       `protobuf:"bytes,9,opt,name=lastModifiedBy,proto3" json:"lastModifiedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Agency) Reset()         { *m = Agency{} }
func (m *Agency) String() string { return proto.CompactTextString(m) }
func (*Agency) ProtoMessage()    {}
func (*Agency) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{4}
}

func (m *Agency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agency.Unmarshal(m, b)
}
func (m *Agency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agency.Marshal(b, m, deterministic)
}
func (m *Agency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agency.Merge(m, src)
}
func (m *Agency) XXX_Size() int {
	return xxx_messageInfo_Agency.Size(m)
}
func (m *Agency) XXX_DiscardUnknown() {
	xxx_messageInfo_Agency.DiscardUnknown(m)
}

var xxx_messageInfo_Agency proto.InternalMessageInfo

func (m *Agency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agency) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Agency) GetTaxCode() string {
	if m != nil {
		return m.TaxCode
	}
	return ""
}

func (m *Agency) GetRepresentativeName() string {
	if m != nil {
		return m.RepresentativeName
	}
	return ""
}

func (m *Agency) GetStatus() AgencyStatus {
	if m != nil {
		return m.Status
	}
	return AgencyStatus_PENDING
}

func (m *Agency) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Agency) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Agency) GetLastModifiedAt() string {
	if m != nil {
		return m.LastModifiedAt
	}
	return ""
}

func (m *Agency) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

type UpdateProfileRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=account.Gender" json:"gender,omitempty"`
	PhoneVerify          string   `protobuf:"bytes,5,opt,name=phoneVerify,proto3" json:"phoneVerify,omitempty"`
	EmailVerify          string   `protobuf:"bytes,6,opt,name=emailVerify,proto3" json:"emailVerify,omitempty"`
	Address              string   `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Dob                  string   `protobuf:"bytes,8,opt,name=dob,proto3" json:"dob,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProfileRequest) Reset()         { *m = UpdateProfileRequest{} }
func (m *UpdateProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProfileRequest) ProtoMessage()    {}
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{5}
}

func (m *UpdateProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProfileRequest.Unmarshal(m, b)
}
func (m *UpdateProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProfileRequest.Merge(m, src)
}
func (m *UpdateProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProfileRequest.Size(m)
}
func (m *UpdateProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProfileRequest proto.InternalMessageInfo

func (m *UpdateProfileRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateProfileRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateProfileRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateProfileRequest) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

func (m *UpdateProfileRequest) GetPhoneVerify() string {
	if m != nil {
		return m.PhoneVerify
	}
	return ""
}

func (m *UpdateProfileRequest) GetEmailVerify() string {
	if m != nil {
		return m.EmailVerify
	}
	return ""
}

func (m *UpdateProfileRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpdateProfileRequest) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

type ChangePasswordRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{6}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ForgotPasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	QuestionSecurity     string   `protobuf:"bytes,2,opt,name=questionSecurity,proto3" json:"questionSecurity,omitempty"`
	AnswerSecurity       string   `protobuf:"bytes,3,opt,name=answerSecurity,proto3" json:"answerSecurity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{7}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ForgotPasswordRequest) GetQuestionSecurity() string {
	if m != nil {
		return m.QuestionSecurity
	}
	return ""
}

func (m *ForgotPasswordRequest) GetAnswerSecurity() string {
	if m != nil {
		return m.AnswerSecurity
	}
	return ""
}

type ResetPasswordRequest struct {
	ResetCode            string   `protobuf:"bytes,1,opt,name=resetCode,proto3" json:"resetCode,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{8}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetResetCode() string {
	if m != nil {
		return m.ResetCode
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LockUserRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ExpiredAt            string   `protobuf:"bytes,3,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockUserRequest) Reset()         { *m = LockUserRequest{} }
func (m *LockUserRequest) String() string { return proto.CompactTextString(m) }
func (*LockUserRequest) ProtoMessage()    {}
func (*LockUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{9}
}

func (m *LockUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockUserRequest.Unmarshal(m, b)
}
func (m *LockUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockUserRequest.Marshal(b, m, deterministic)
}
func (m *LockUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockUserRequest.Merge(m, src)
}
func (m *LockUserRequest) XXX_Size() int {
	return xxx_messageInfo_LockUserRequest.Size(m)
}
func (m *LockUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockUserRequest proto.InternalMessageInfo

func (m *LockUserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LockUserRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *LockUserRequest) GetExpiredAt() string {
	if m != nil {
		return m.ExpiredAt
	}
	return ""
}

type GetUserInfoRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRequest) Reset()         { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()    {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{10}
}

func (m *GetUserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRequest.Unmarshal(m, b)
}
func (m *GetUserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRequest.Merge(m, src)
}
func (m *GetUserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRequest.Size(m)
}
func (m *GetUserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRequest proto.InternalMessageInfo

func (m *GetUserInfoRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserInfoResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=account.Gender" json:"gender,omitempty"`
	PhoneVerify          string   `protobuf:"bytes,5,opt,name=phoneVerify,proto3" json:"phoneVerify,omitempty"`
	EmailVerify          string   `protobuf:"bytes,6,opt,name=emailVerify,proto3" json:"emailVerify,omitempty"`
	Address              string   `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Dob                  string   `protobuf:"bytes,8,opt,name=dob,proto3" json:"dob,omitempty"`
	ActivatedAt          string   `protobuf:"bytes,9,opt,name=activatedAt,proto3" json:"activatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{11}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserInfoResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserInfoResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserInfoResponse) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_MALE
}

func (m *UserInfoResponse) GetPhoneVerify() string {
	if m != nil {
		return m.PhoneVerify
	}
	return ""
}

func (m *UserInfoResponse) GetEmailVerify() string {
	if m != nil {
		return m.EmailVerify
	}
	return ""
}

func (m *UserInfoResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserInfoResponse) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *UserInfoResponse) GetActivatedAt() string {
	if m != nil {
		return m.ActivatedAt
	}
	return ""
}

type PageRequest struct {
	PageNumber           int32    `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Sort                 *Sort    `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{12}
}

func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *PageRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PageRequest) GetSort() *Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type Sort struct {
	Direction            string   `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	Properties           []string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sort) Reset()         { *m = Sort{} }
func (m *Sort) String() string { return proto.CompactTextString(m) }
func (*Sort) ProtoMessage()    {}
func (*Sort) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{13}
}

func (m *Sort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sort.Unmarshal(m, b)
}
func (m *Sort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sort.Marshal(b, m, deterministic)
}
func (m *Sort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sort.Merge(m, src)
}
func (m *Sort) XXX_Size() int {
	return xxx_messageInfo_Sort.Size(m)
}
func (m *Sort) XXX_DiscardUnknown() {
	xxx_messageInfo_Sort.DiscardUnknown(m)
}

var xxx_messageInfo_Sort proto.InternalMessageInfo

func (m *Sort) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *Sort) GetProperties() []string {
	if m != nil {
		return m.Properties
	}
	return nil
}

type PageResponse struct {
	TotalItems           int64    `protobuf:"varint,1,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageResponse) Reset()         { *m = PageResponse{} }
func (m *PageResponse) String() string { return proto.CompactTextString(m) }
func (*PageResponse) ProtoMessage()    {}
func (*PageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d66906c5773c9d08, []int{14}
}

func (m *PageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResponse.Unmarshal(m, b)
}
func (m *PageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResponse.Marshal(b, m, deterministic)
}
func (m *PageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResponse.Merge(m, src)
}
func (m *PageResponse) XXX_Size() int {
	return xxx_messageInfo_PageResponse.Size(m)
}
func (m *PageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PageResponse proto.InternalMessageInfo

func (m *PageResponse) GetTotalItems() int64 {
	if m != nil {
		return m.TotalItems
	}
	return 0
}

func (m *PageResponse) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *PageResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func init() {
	proto.RegisterEnum("account.AgencyStatus", AgencyStatus_name, AgencyStatus_value)
	proto.RegisterEnum("account.Gender", Gender_name, Gender_value)
	proto.RegisterType((*CreateAgencyRequest)(nil), "account.CreateAgencyRequest")
	proto.RegisterType((*UpdateAgencyRequest)(nil), "account.UpdateAgencyRequest")
	proto.RegisterType((*GetAgencyRequest)(nil), "account.GetAgencyRequest")
	proto.RegisterType((*GetAgencyResponse)(nil), "account.GetAgencyResponse")
	proto.RegisterType((*Agency)(nil), "account.Agency")
	proto.RegisterType((*UpdateProfileRequest)(nil), "account.UpdateProfileRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "account.ChangePasswordRequest")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "account.ForgotPasswordRequest")
	proto.RegisterType((*ResetPasswordRequest)(nil), "account.ResetPasswordRequest")
	proto.RegisterType((*LockUserRequest)(nil), "account.LockUserRequest")
	proto.RegisterType((*GetUserInfoRequest)(nil), "account.GetUserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "account.UserInfoResponse")
	proto.RegisterType((*PageRequest)(nil), "account.PageRequest")
	proto.RegisterType((*Sort)(nil), "account.Sort")
	proto.RegisterType((*PageResponse)(nil), "account.PageResponse")
}

func init() {
	proto.RegisterFile("account/account.proto", fileDescriptor_d66906c5773c9d08)
}

var fileDescriptor_d66906c5773c9d08 = []byte{
	// 1066 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0xcd, 0x72, 0xe3, 0x44,
	0x10, 0x5e, 0xcb, 0x7f, 0x71, 0x3b, 0xc9, 0x9a, 0xd9, 0x38, 0x65, 0x4c, 0xd8, 0x5a, 0x54, 0x05,
	0x84, 0xc0, 0x3a, 0x55, 0xe1, 0x08, 0x17, 0x27, 0x71, 0x42, 0x8a, 0x5d, 0xe3, 0x52, 0x36, 0x4b,
	0x15, 0x17, 0x4a, 0xb1, 0xda, 0x5a, 0x81, 0xad, 0x11, 0xa3, 0x71, 0xb2, 0xe1, 0x04, 0x27, 0x1e,
	0x84, 0x57, 0xe0, 0xc6, 0xb3, 0xf0, 0x1e, 0x1c, 0xa9, 0xf9, 0x91, 0x34, 0x96, 0x65, 0x27, 0x37,
	0x28, 0x4e, 0x71, 0x7f, 0xdd, 0xd3, 0x9a, 0xfe, 0xa6, 0xfb, 0x9b, 0x09, 0xb4, 0xdd, 0xf1, 0x98,
	0xce, 0x43, 0x7e, 0xa8, 0xff, 0xf6, 0x22, 0x46, 0x39, 0x25, 0x75, 0x6d, 0x76, 0xdf, 0xf3, 0x29,
	0xf5, 0xa7, 0x78, 0x28, 0xe1, 0xeb, 0xf9, 0xe4, 0x10, 0x67, 0x11, 0xbf, 0x53, 0x51, 0xf6, 0x5f,
	0x16, 0x3c, 0x39, 0x61, 0xe8, 0x72, 0xec, 0xfb, 0x18, 0x8e, 0xef, 0x1c, 0xfc, 0x69, 0x8e, 0x31,
	0x27, 0x04, 0x2a, 0xa1, 0x3b, 0xc3, 0x4e, 0xe9, 0x59, 0x69, 0xbf, 0xe1, 0xc8, 0xdf, 0xa4, 0x03,
	0x75, 0xd7, 0xf3, 0x18, 0xc6, 0x71, 0xc7, 0x92, 0x70, 0x62, 0x0a, 0x0f, 0x77, 0xdf, 0x9e, 0x50,
	0x0f, 0x3b, 0x65, 0xe5, 0xd1, 0x26, 0xe9, 0x01, 0x61, 0x18, 0x31, 0x8c, 0x31, 0xe4, 0x2e, 0x0f,
	0x6e, 0x70, 0x28, 0xb2, 0x56, 0x64, 0x50, 0x81, 0x87, 0x74, 0x61, 0x63, 0x1e, 0x23, 0x93, 0xdf,
	0xae, 0xca, 0xa8, 0xd4, 0x16, 0xbe, 0xc8, 0x8d, 0xe3, 0x5b, 0xca, 0xbc, 0x4e, 0x4d, 0xf9, 0x12,
	0x9b, 0x3c, 0x83, 0x66, 0xf4, 0x86, 0x86, 0xf8, 0x1a, 0x59, 0x30, 0xb9, 0xeb, 0xd4, 0xa5, 0xdb,
	0x84, 0x44, 0x04, 0xce, 0xdc, 0x60, 0xaa, 0x23, 0x36, 0x54, 0x84, 0x01, 0x91, 0x03, 0x68, 0xc9,
	0xe2, 0x03, 0x1a, 0x5e, 0xe2, 0x78, 0xce, 0x02, 0x7e, 0xd7, 0x69, 0xc8, 0xb0, 0x25, 0x9c, 0x7c,
	0x04, 0xdb, 0x6e, 0x18, 0xdf, 0x22, 0x4b, 0x23, 0x41, 0x46, 0xe6, 0x50, 0xfb, 0xef, 0x12, 0x3c,
	0xb9, 0x8a, 0xbc, 0x25, 0x7e, 0xbb, 0xb0, 0xe1, 0x4a, 0xe0, 0xc2, 0x93, 0x1c, 0x97, 0x9d, 0xd4,
	0x4e, 0xb9, 0xb7, 0x8a, 0xb9, 0x2f, 0xaf, 0xe4, 0xbe, 0xf2, 0x10, 0xee, 0xab, 0x2b, 0xb9, 0x7f,
	0x0e, 0xb5, 0x98, 0xbb, 0x7c, 0x1e, 0x4b, 0x76, 0xb7, 0x8f, 0xda, 0xbd, 0xa4, 0xa3, 0xd4, 0xde,
	0x2f, 0xa5, 0xd3, 0xd1, 0x41, 0xe4, 0x29, 0xc0, 0xd8, 0x65, 0xde, 0x70, 0x3e, 0xbb, 0x46, 0xa6,
	0x19, 0x37, 0x10, 0xfb, 0x8f, 0x12, 0xb4, 0xce, 0x91, 0xff, 0x37, 0xfa, 0x6a, 0x1f, 0x2a, 0x91,
	0xeb, 0xab, 0xea, 0x9b, 0x47, 0x3b, 0x69, 0x65, 0x23, 0xd7, 0x47, 0xbd, 0x37, 0x47, 0x46, 0xd8,
	0x08, 0xef, 0x18, 0xbb, 0x8e, 0x23, 0x1a, 0xc6, 0x48, 0x3e, 0xd1, 0xcb, 0x4b, 0x72, 0x79, 0x3b,
	0xb7, 0x5c, 0x05, 0xa9, 0xf5, 0xe4, 0x43, 0xa8, 0x06, 0x1c, 0x67, 0xa2, 0x96, 0xf2, 0x7e, 0xf3,
	0xe8, 0x71, 0x8e, 0x44, 0x47, 0x79, 0xed, 0x3f, 0x2d, 0xa8, 0x29, 0xe4, 0x5f, 0xe3, 0x24, 0x3b,
	0xef, 0xea, 0x43, 0xce, 0x7b, 0x0f, 0x1a, 0x63, 0xa9, 0x14, 0x5e, 0x9f, 0xeb, 0xf9, 0xcb, 0x00,
	0xc3, 0x7b, 0x9c, 0x8c, 0x5f, 0x06, 0x88, 0x71, 0x99, 0xba, 0x31, 0x7f, 0x49, 0xbd, 0x60, 0x12,
	0xc8, 0x04, 0x6a, 0xfe, 0x72, 0x68, 0x3e, 0xee, 0x38, 0x19, 0xc0, 0x1c, 0x6a, 0xff, 0x6a, 0xc1,
	0x8e, 0x1a, 0xab, 0x11, 0xa3, 0x93, 0x60, 0x9a, 0x9c, 0x21, 0xd9, 0x85, 0x9a, 0xd0, 0x8b, 0x74,
	0xaa, 0xb4, 0x25, 0xb6, 0x37, 0x09, 0x58, 0xcc, 0x87, 0xd9, 0x60, 0x65, 0x80, 0x98, 0x46, 0xf1,
	0x01, 0xe9, 0x54, 0xa4, 0xa6, 0x36, 0xf9, 0x18, 0x6a, 0x3e, 0x86, 0x1e, 0x32, 0xc9, 0xe4, 0xb6,
	0x71, 0xa0, 0xe7, 0x12, 0x76, 0xb4, 0x3b, 0x2f, 0x41, 0xd5, 0x7b, 0x25, 0xa8, 0xb6, 0x2c, 0x41,
	0xc6, 0xb1, 0xd7, 0x17, 0x8f, 0xbd, 0x05, 0x65, 0x8f, 0x5e, 0x6b, 0xda, 0xc4, 0x4f, 0x7b, 0x06,
	0xed, 0x93, 0x37, 0x6e, 0xe8, 0xe3, 0x48, 0x8b, 0xe0, 0x7d, 0x1c, 0x98, 0xfa, 0x69, 0x2d, 0xeb,
	0x67, 0x88, 0xb7, 0x49, 0x26, 0x4d, 0x82, 0x09, 0xd9, 0xbf, 0x95, 0xa0, 0x7d, 0x46, 0x99, 0x4f,
	0x79, 0xfe, 0x7b, 0xa6, 0x66, 0x97, 0x72, 0x9a, 0x5d, 0xa4, 0xa9, 0xd6, 0x83, 0x35, 0xb5, 0x5c,
	0xa8, 0xa9, 0x23, 0xd8, 0x71, 0x30, 0xc6, 0xa5, 0x7d, 0xec, 0x41, 0x43, 0xb4, 0x38, 0x97, 0xb3,
	0xa1, 0x36, 0x92, 0x01, 0xeb, 0xaa, 0xb7, 0xbf, 0x87, 0xc7, 0x2f, 0xe8, 0xf8, 0xc7, 0xab, 0x18,
	0xd9, 0x7d, 0x24, 0xee, 0x42, 0x8d, 0xa1, 0x1b, 0xd3, 0x50, 0x27, 0xd1, 0x96, 0xf8, 0x38, 0xbe,
	0x8d, 0x02, 0x26, 0x9b, 0x5b, 0xed, 0x3b, 0x03, 0xec, 0xcf, 0x80, 0x9c, 0x23, 0x17, 0xf9, 0x2f,
	0xc2, 0x09, 0xbd, 0xe7, 0x1b, 0xf6, 0xef, 0x16, 0xb4, 0xb2, 0x58, 0x2d, 0x41, 0xeb, 0x58, 0xfe,
	0xff, 0x75, 0xb7, 0xc8, 0xe6, 0x8e, 0x79, 0x70, 0xa3, 0xf5, 0x46, 0xc9, 0x80, 0x09, 0xd9, 0x53,
	0x68, 0x1a, 0xea, 0x2d, 0xae, 0x23, 0xa1, 0xbf, 0xfa, 0x3a, 0x12, 0x0c, 0x55, 0x1d, 0x03, 0x51,
	0xe7, 0xef, 0xe3, 0x65, 0xf0, 0xb3, 0xa2, 0xa8, 0xea, 0xa4, 0x36, 0xf9, 0x00, 0x2a, 0x31, 0x65,
	0xea, 0xdc, 0x9a, 0x47, 0x5b, 0x29, 0x07, 0x97, 0x94, 0x71, 0x47, 0xba, 0xec, 0x53, 0xa8, 0x08,
	0x4b, 0x50, 0xed, 0x05, 0x0c, 0xc7, 0xa2, 0x73, 0x93, 0x26, 0x4b, 0x01, 0xb9, 0x09, 0x46, 0x23,
	0x64, 0x3c, 0x40, 0x75, 0x03, 0x34, 0x1c, 0x03, 0xb1, 0x7f, 0x80, 0x4d, 0xf3, 0xca, 0x10, 0xf1,
	0x9c, 0x72, 0x77, 0x7a, 0x21, 0x6f, 0x0c, 0xd5, 0x05, 0x06, 0x92, 0x2b, 0xca, 0x5a, 0x5b, 0x54,
	0x79, 0xb1, 0xa8, 0x83, 0x2f, 0x60, 0xd3, 0xd4, 0x71, 0xd2, 0x84, 0xfa, 0x68, 0x30, 0x3c, 0xbd,
	0x18, 0x9e, 0xb7, 0x1e, 0x91, 0x2d, 0x68, 0xf4, 0x4f, 0x5e, 0x5d, 0xbc, 0xee, 0xbf, 0x1a, 0x9c,
	0xb6, 0x4a, 0xe4, 0x31, 0x34, 0x4f, 0x07, 0x19, 0x60, 0x1d, 0x7c, 0x0a, 0x35, 0xd5, 0x00, 0x64,
	0x03, 0x2a, 0x2f, 0xfb, 0x2f, 0x06, 0xad, 0x47, 0x04, 0xa0, 0x76, 0x36, 0x90, 0xbf, 0x4b, 0x22,
	0xd9, 0xd5, 0xf0, 0xeb, 0xe1, 0x37, 0xdf, 0x0e, 0x5b, 0xd6, 0xd1, 0x2f, 0x55, 0xa8, 0xf7, 0x15,
	0x65, 0xe4, 0x14, 0x36, 0xcd, 0xf7, 0x24, 0xd9, 0x4b, 0xc9, 0x2c, 0x78, 0x66, 0x76, 0x77, 0x7b,
	0xea, 0x71, 0xda, 0x4b, 0x1e, 0xa7, 0xbd, 0x81, 0x78, 0x9c, 0x8a, 0x2c, 0xe6, 0xab, 0xc9, 0xc8,
	0x52, 0xf0, 0x98, 0x5a, 0x99, 0xe5, 0x18, 0x1a, 0xe9, 0x55, 0x4e, 0xde, 0x35, 0x3a, 0x7b, 0xf1,
	0x51, 0xd2, 0xed, 0x16, 0xb9, 0xf4, 0x09, 0x9d, 0x40, 0xd3, 0x98, 0xdc, 0x75, 0x59, 0x32, 0xd7,
	0xd2, 0xec, 0x9e, 0xc1, 0xd6, 0xc2, 0x6d, 0x45, 0xde, 0xcf, 0xd5, 0xb3, 0x78, 0x8b, 0xad, 0x2c,
	0xe8, 0x2b, 0xd8, 0x5e, 0x94, 0x7c, 0xf2, 0x34, 0xa3, 0xb7, 0xe8, 0x2e, 0x58, 0x97, 0x69, 0x51,
	0xcc, 0x8d, 0x4c, 0x85, 0x2a, 0xbf, 0x32, 0xd3, 0x19, 0x6c, 0x2d, 0xa8, 0xb1, 0x51, 0x5b, 0x91,
	0x4a, 0xaf, 0xcc, 0xf3, 0x25, 0x6c, 0x24, 0x1a, 0x4c, 0x3a, 0x69, 0x8a, 0x9c, 0x2c, 0xaf, 0x5a,
	0x7d, 0xdc, 0x87, 0x0e, 0x65, 0x7e, 0xef, 0x86, 0xde, 0xd0, 0x9e, 0xcf, 0xa2, 0xb1, 0x8f, 0x61,
	0x92, 0xe3, 0x78, 0x53, 0xf7, 0xe6, 0x48, 0x2c, 0x19, 0x95, 0xbe, 0x6b, 0x8b, 0xa8, 0x43, 0x11,
	0xf5, 0xdc, 0xc7, 0x30, 0xf9, 0xb7, 0xe9, 0xba, 0x26, 0x53, 0x7e, 0xfe, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x9e, 0x16, 0xbf, 0xbf, 0x50, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	CreateAgency(ctx context.Context, in *CreateAgencyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateAgency(ctx context.Context, in *UpdateAgencyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetAgency(ctx context.Context, in *GetAgencyRequest, opts ...grpc.CallOption) (*GetAgencyResponse, error)
	GetUserInfo(ctx context.Context, in *GetAgencyRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	LockUser(ctx context.Context, in *LockUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type accountClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountClient(cc grpc.ClientConnInterface) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) CreateAgency(ctx context.Context, in *CreateAgencyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Account/CreateAgency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateAgency(ctx context.Context, in *UpdateAgencyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Account/UpdateAgency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetAgency(ctx context.Context, in *GetAgencyRequest, opts ...grpc.CallOption) (*GetAgencyResponse, error) {
	out := new(GetAgencyResponse)
	err := c.cc.Invoke(ctx, "/account.Account/GetAgency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUserInfo(ctx context.Context, in *GetAgencyRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/account.Account/GetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Account/UpdateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Account/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Account/ForgotPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Account/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) LockUser(ctx context.Context, in *LockUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/account.Account/LockUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	CreateAgency(context.Context, *CreateAgencyRequest) (*empty.Empty, error)
	UpdateAgency(context.Context, *UpdateAgencyRequest) (*empty.Empty, error)
	GetAgency(context.Context, *GetAgencyRequest) (*GetAgencyResponse, error)
	GetUserInfo(context.Context, *GetAgencyRequest) (*UserInfoResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*empty.Empty, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*empty.Empty, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*empty.Empty, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*empty.Empty, error)
	LockUser(context.Context, *LockUserRequest) (*empty.Empty, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) CreateAgency(ctx context.Context, req *CreateAgencyRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgency not implemented")
}
func (*UnimplementedAccountServer) UpdateAgency(ctx context.Context, req *UpdateAgencyRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgency not implemented")
}
func (*UnimplementedAccountServer) GetAgency(ctx context.Context, req *GetAgencyRequest) (*GetAgencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgency not implemented")
}
func (*UnimplementedAccountServer) GetUserInfo(ctx context.Context, req *GetAgencyRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedAccountServer) UpdateProfile(ctx context.Context, req *UpdateProfileRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (*UnimplementedAccountServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedAccountServer) ForgotPassword(ctx context.Context, req *ForgotPasswordRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (*UnimplementedAccountServer) ResetPassword(ctx context.Context, req *ResetPasswordRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}
func (*UnimplementedAccountServer) LockUser(ctx context.Context, req *LockUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockUser not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_CreateAgency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).CreateAgency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/CreateAgency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).CreateAgency(ctx, req.(*CreateAgencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateAgency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateAgency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/UpdateAgency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateAgency(ctx, req.(*UpdateAgencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetAgency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetAgency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetAgency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetAgency(ctx, req.(*GetAgencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUserInfo(ctx, req.(*GetAgencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/UpdateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/ForgotPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_LockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).LockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/LockUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).LockUser(ctx, req.(*LockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgency",
			Handler:    _Account_CreateAgency_Handler,
		},
		{
			MethodName: "UpdateAgency",
			Handler:    _Account_UpdateAgency_Handler,
		},
		{
			MethodName: "GetAgency",
			Handler:    _Account_GetAgency_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _Account_GetUserInfo_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _Account_UpdateProfile_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Account_ChangePassword_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _Account_ForgotPassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _Account_ResetPassword_Handler,
		},
		{
			MethodName: "LockUser",
			Handler:    _Account_LockUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/account.proto",
}
